- name: Deploy a web application
  hosts: ubuntu01
  tasks:
    - name: "install all dependices"
      apt: name={{ item }} state=present
      with_items:
        - python
        - python-setuptools
        - python-dev
        - build-essential
        - python-pip
        - python-mysqldb
    - name: "install database"
      apt: name={{ item }} state=present
      with_items:
        - mysql-server
        - mysql-client
    - name: "start database"
      service:
        name: mysql
        state: started
        enabled: yes
    - name: "Create application database"
      mysql_db: name=employee_db state=present
    - name: "Create user"
      mysql_user:
        name: db_user
        password: Passw0rd
        priv: '*.*:ALL'
        state: present
    - name: "Install Python Flask dependices"
      pip:
        name: "{{ item }}"
        state: present
      with_items:
        - flask
        - flask-mysql
    - name: "copy code"
      copy: src=app.py dest=/opt/app.py
    - name: "start seb server"
      shell: FLASK_APP=app.py nohup flask run --host=0.0.0.0 &
