---
# same config file
- hosts: all
  remote_user: root
  tasks:
          # create a new file on each host
          - copy:
              content: "ansible ALL=(ALL)   NOPASSWD:ALL"
              dest: "/etc/sudoers.d/ansible"
